var Icon = {};
Icon.Base		= L.icon({iconUrl:'./img/markers/IconBase.png',		iconSize:[19,23],});Icon.Base.name	= 'База';
Icon.City		= L.icon({iconUrl:'./img/markers/IconCity.png',		iconSize:[77/1.5,71/1.5],});Icon.City.name = 'Город';
Icon.Fort		= L.icon({iconUrl:'./img/markers/IconFort.png',		iconSize:[45,68],});Icon.Fort.name	= 'Форт';
Icon.Mine		= L.icon({iconUrl:'./img/markers/IconMine.png',		iconSize:[36,28],});Icon.Mine.name	= 'Шахта';
Icon.Ruins		= L.icon({iconUrl:'./img/markers/IconRuins.png',	iconSize:[22,34],});Icon.Ruins.name	= 'Руины';
Icon.RuinsLab	= L.icon({iconUrl:'./img/markers/IconRuins.png',	iconSize:[22,34],});Icon.Ruins.name	= 'Руины Библиотеки';
Icon.Village	= L.icon({iconUrl:'./img/markers/IconVillage.png',	iconSize:[32,32],});Icon.Village.name	= 'Деревня';

var arr_markers = [
{type:'City',	nameRU:'Адмаг',				name:'Admag',			x:447, y:197,	title:'<i>Королевство шеков</i><br>Столица фракции, находящаяся в северной области региона Пустыня Стэнн, прямо на возвышенности. Здесь можно отыскать башню Гильдии Воров.<a href="https://kenshi.fandom.com/ru/wiki/Адмаг" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Акула',				name:'Shark',			x:334, y:340,	title:'Находится в Болотах и является пристанищем 5 разных банд.<a href="https://kenshi.fandom.com/ru/wiki/Акула" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Барк',				name:'Bark',			x:869, y:798,	title:'<i>Союзные Города</i><br>Прибрежный населенный пункт, находящийся в районе, именуемом Великая пустыня.<a href="https://kenshi.fandom.com/ru/wiki/Барк" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Безродный',			name:'Mongrel',			x:625, y:219,	title:'<i>Безродный</i><br>Можно найти в западной области карты, в центральной части Туманных островов. Имеет немало магазинов с редкими товарами.<a href="https://kenshi.fandom.com/ru/wiki/Безродный_(город)" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Бугристый Холм',	name:'Blister Hill',	x:646, y:373,	title:'<i>Святая Нация</i><br>Столица фракции, находящаяся на северо-востоке центральной области мира и способный похвастаться большим количеством различных магазинов.<a href="https://kenshi.fandom.com/ru/wiki/Бугристый_Холм" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Выдержка Скитальца',name:"Drifter's Last",	x:109, y:228,	title:'<i>Союзные Города</i><br>Находится в юго-западной области мира в регионе под названием Крюк. Рядом с ним можно найти фермы, из-за которых в окрестностях часто встречаются фермеры-мятежники.<a href="https://kenshi.fandom.com/ru/wiki/Выдержка_Скитальца" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Грань',				name:'Brink',			x:480, y:710,	title:'<i>Союзные Города</i><br>можно отыскать в восточной области карты в регионе под названием Берег грозоого ущелья.<a href="https://kenshi.fandom.com/ru/wiki/Грань" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Груз',				name:'Heft',			x:741, y:734,	title:'<i>Союзные Города</i><br>Столица фракции Расположена на южной части Великой пустыни.<a href="https://kenshi.fandom.com/ru/wiki/Груз" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Катун',				name:'Catun',			x:221, y:476,	title:'<i>Союзные Города</i><br>Находится в регионе под названием Поля костей. Знаменит своим магазином оружия Катунских Мастеров.<a href="https://kenshi.fandom.com/ru/wiki/Катун" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Клаунстэди',		name:'Clownsteady',		x:187, y:291,	title:'<i>Союзные Города</i><br>Находится в юго-западной области мира на границе региона Южные болота.<a href="https://kenshi.fandom.com/ru/wiki/Клаунстэди" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Край Мира',			name:"World's End",		x:791, y:416,	title:'<i>Техохотники</i><br>Столица фракции, находящаяся в Руке Окрана. Знаменита своим университетом Машинистов, хранящим в себе разные артефакты и технологические вещи.<a href="https://kenshi.fandom.com/ru/wiki/Край_Мира" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Плохие Зубы',		name:'Bad Teeth',		x:566, y:386,	title:'<i>Святая Нация</i><br>Хорошо защищенный город, который можно отыскать на горном перевале «зеленой» зоны Гордость Окрана.<a href="https://kenshi.fandom.com/ru/wiki/Плохие_Зубы" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Ровная лагуна',		name:'Flats Lagoon',	x:337, y:564,	title:'<i>Техохотники</i><br>Находится в одноименном районе, к востоку от болота.<a href="https://kenshi.fandom.com/ru/wiki/Ровная_лагуна_(город)" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Рыбный остров',		name:'Fish Isle',		x:87,  y:471,	title:'<i>Рыболюды</i><br>Остров в южной части мира Кеньши. Населён агрессивно настроенными Рыболюдами<a href="https://kenshi.fandom.com/ru/wiki/Рыбный_остров" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Скачок',			name:'Spring',			x:288, y:679,	title:'<i>Протиники рабства</i><br>Находится в регионе Авантюра Стоба. Тут обитают противники работорговли.<a href="https://kenshi.fandom.com/ru/wiki/Скачок" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Скуин',				name:'Squin',			x:445, y:288,	title:'<i>Королевство шеков</i><br>можно отыскать в западной области Пограничной Зоны. В нем имеются бары и базовые магазины. Здесь имеются сравнительно безопасные месторождения меди и железа.<a href="https://kenshi.fandom.com/ru/wiki/Скуин" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Ссылка Кат-Лона',	name:"Cat-Lon's Exile",	x:74,  y:858,	title:'<i>Изгнанники ВИ</i><br>Место ссылки императора Второй Империи в Пепельных землях<a href="https://kenshi.fandom.com/ru/wiki/Ссылка_Кат-Лона" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Стоат',				name:'Stoat',			x:740, y:617,	title:'<i>Союзные Города</i><br>Расположен в юго-западной области Великой пустыни.<a href="https://kenshi.fandom.com/ru/wiki/Стоат" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Столица людоедов',	name:'Cannibal Capital',x:875, y:289,	title:'<i>Людоеды</i><br>В северо-западной области мира есть Равнины людоедов. А это — их столица.<a href="https://kenshi.fandom.com/ru/wiki/Столица_людоедов" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Стопка',			name:'Stack',			x:542, y:309,	title:'<i>Святая Нация</i><br>Большое поселение, которое базируется в юго-восточной области центральной части мира на границе фракции. Находится неподалеку от Хаба и Западного Улья, поэтому является неплохим местом для воров и торговцев.<a href="https://kenshi.fandom.com/ru/wiki/Стопка" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Траур',				name:'Mourn',			x:278, y:542,	title:'<i>Техохотники</i><br>Полуразрушенное поселение, находящееся в районе Поля костей. Тут обитает Большой Белый Горилло.<a href="https://kenshi.fandom.com/ru/wiki/Траур" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Хаб',				name:'The Hub',			x:488, y:326,	title:'<i>Изгои Святой Нации</i><br>Разрушен в ходе войны между КШ и СН, находится в западной области карты в регионе под названием Пограничье. Тут обитают различные преступники и изгои.<a href="https://kenshi.fandom.com/ru/wiki/Хаб" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Хэн',				name:'Heng',			x:641, y:663,	title:'<i>Союзные Города</i><br>Укрепленный населенный пункт, основанный в районе Хэн.<a href="https://kenshi.fandom.com/ru/wiki/Хэн_(город)" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Чёрная пустыня',	name:'Black Desert City',x:543,y:529,	title:'<i>Скелеты</i><br>Находится в центральной области Мертвых земель. Тут обитают скелеты.<a href="https://kenshi.fandom.com/ru/wiki/Чёрная_пустыня_(город)" target="_blank">На Wiki</a>'},
{type:'City',	nameRU:'Чёрная Ссадина',	name:'Black Scratch',	x:483, y:789,	title:'<i>Техохотники</i><br>Находится в восточной области карты в Дальних землях. Она славится своей Большой библиотекой, в которой хранятся самые разнообразные чертежи и книги.<a href="https://kenshi.fandom.com/ru/wiki/Чёрная_Ссадина" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Шо-Баттаи',			name:'Sho-Battai',		x:819, y:682,	title:'<i>Союзные Города</i><br>Крупный городфракции. Можно отыскать в центре Великой пустыни.<a href="https://kenshi.fandom.com/ru/wiki/Шо-Баттаи" target="_blank">На Wiki</a>'}, 
{type:'City',	nameRU:'Южный улей',		name:'Southern Hive',	x:145, y:615,	title:'<i>Южный Улей</i><br>Поселение Южного Улья в южных землях. Будьте осторожны, их король жаждет свежего мяса :)<a href="https://kenshi.fandom.com/ru/wiki/Южный_улей_(город)" target="_blank">На Wiki</a>'},

{type:'Base',	nameRU:'Застава стражников',		name:'Guard Outpost',		x:796.8, y:511.8,	title:'Описание'}, 
{type:'Base',	nameRU:'Застава стражников',		name:'Guard Outpost',		x:827.6, y:512.5,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:789.1, y:522.9,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:801.9, y:513.1,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:802.7, y:566.8,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:806.8, y:537.6,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:810.8, y:499.1,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:814.2, y:552.7,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:822.3, y:559.4,	title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:825.2, y:530,		title:'Описание'}, 
{type:'Base',	nameRU:'Разорённая деревня',		name:'Ravaged Hamlet',		x:841.7, y:549.2,	title:'Описание'}, 
{type:'Base',	nameRU:'База Болотных Ниндзя',		name:'Swamp Ninja Base',	x:256.6, y:359.7,	title:'Описание'}, 
{type:'Base',	nameRU:'База Мятежников',			name:'Rebel Base',			x:503.6, y:328.2,	title:'Описание'}, 
{type:'Base',	nameRU:'Бар контрабандистов',		name:'Smugglers Bar',		x:451.5, y:502,		title:'Описание'}, 
{type:'Base',	nameRU:'Башня Козлов',				name:'Tower Of Goats',		x:961.2, y:557,		title:'Описание'}, 
{type:'Base',	nameRU:'Башня Ниндзя',				name:'Tower Of Ninjas',		x:520.7, y:407.7,	title:'Описание'}, 
{type:'Base',	nameRU:'Башня Пыльного Короля',		name:'Dust King Tower',		x:502.3, y:377.3,	title:'Описание'}, 
{type:'Base',	nameRU:'Башня Тумана',				name:'Tower of Fog',		x:474.7, y:56.3,	title:'Описание'}, 
{type:'Base',	nameRU:'Башня пауков',				name:'Tower of Spiders',	x:336.5, y:874.3,	title:'Описание'}, 
{type:'Base',	nameRU:'Башня снайперов',			name:'Sniper Tower',		x:230.1, y:864.1,	title:'Описание'}, 
{type:'Base',	nameRU:'Забытый трон',				name:'The Forgotten Throne',x:289.7, y:102.2,	title:'Описание'}, 
{type:'Base',	nameRU:'Лагерь изгнанников',		name:'Exile Camp',			x:400.6, y:257.4,	title:'Описание'}, 
{type:'Base',	nameRU:'Логово Кактуса',			name:'Cactus Den',			x:698.8, y:552.5,	title:'Описание'}, 
{type:'Base',	nameRU:'Остров Ящера',				name:'Raptor Island',		x:712, y:97.2,		title:'Описание'}, 
{type:'Base',	nameRU:'Пустая развалина',			name:'Empty Ruin',			x:249.2, y:319.5,	title:'Описание'}, 
{type:'Base',	nameRU:'Пустая развалина',			name:'Empty Ruin',			x:284.3, y:489,		title:'Описание'}, 
{type:'Base',	nameRU:'Пустая развалина',			name:'Empty Ruin',			x:289.6, y:287.4,	title:'Описание'}, 
{type:'Base',	nameRU:'Разведпост',				name:'Scout Post',			x:816.4, y:346.2,	title:'Описание'}, 
{type:'Base',	nameRU:'Разведпост',				name:'Scout Post',			x:837.5, y:355.6,	title:'Описание'}, 
{type:'Base',	nameRU:'Старая башня',				name:'Watchtower',			x:769.7, y:484.5,	title:'Описание'}, 
{type:'Base',	nameRU:'Странный лагерь',			name:'Strange Camp',		x:573.8, y:743.5,	title:'Описание'}, 
{type:'Base',	nameRU:'Убежище Отщепенцев',		name:'Flotsam Safehouse',	x:716.6, y:343,		title:'Описание'}, 
{type:'Base',	nameRU:'Хламилище',					name:'Scraphouse',			x:547.5, y:538.5,	title:'Описание <a href="https://kenshi.fandom.com/ru/wiki/Хламилище" target="_blank">На Wiki</a>'}, 
{type:'Base',	nameRU:'Штаб Чёрных Псов',			name:'Black Dog HQ',		x:490.7, y:749,		title:'Описание'}, 
{type:'Base', 	nameRU:'Логово Красных сабель',		name:'Red Sabre Hideout',	x:283.2, y:298.1,	title:'Описание'}, 
{type:'Fort',	nameRU:'База Охотников на людей',	name:'Manhunter Base',		x:161.5, y:358.9,	title:'Описание'}, 
{type:'Fort',	nameRU:'Барьерная башня',			name:'Barrier Tower',		x:223.4, y:790.4,	title:'Описание'}, 
{type:'Fort',	nameRU:'Бастион',					name:'The Bastion',			x:883.3, y:546.5,	title:'Описание'}, 
{type:'Fort',	nameRU:'Великая крепость',			name:'The Great Fortress',	x:413.1,y:204,		title:'Описание'}, 
{type:'Fort',	nameRU:'Город крабов',				name:'Crab Town',			x:318.3, y:979.9,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня Берсерков',			name:'Berserker Village',	x:350.2, y:220.8,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня крабов',			name:'Crab Village',		x:345, y:900.9,		title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня крабов',			name:'Crab Village',		x:436.1, y:935.4,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня людоедов',			name:'Cannibal Village',	x:839.5, y:277.8,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня людоедов',			name:'Cannibal Village',	x:858.3, y:329.3,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня людоедов',			name:'Cannibal Village',	x:867.4, y:255.7,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня людоедов',			name:'Cannibal Village',	x:915.1, y:502.3,	title:'Описание'}, 
{type:'Fort',	nameRU:'Деревня людоедов',			name:'Cannibal Village',	x:935.8, y:461.5,	title:'Описание'}, 
{type:'Fort',	nameRU:'Дом Кожи - Штаб',			name:'Skinhouse HQ',		x:220.1, y:772.5,	title:'Описание'}, 
{type:'Fort',	nameRU:'Дом Кожи',					name:'Skinhouse',			x:126.8, y:767.3,	title:'Описание'}, 
{type:'Fort',	nameRU:'Дом Кожи',					name:'Skinhouse',			x:180, y:749.4,		title:'Описание'}, 
{type:'Fort',	nameRU:'Железный штаб',				name:'Iron HQ',				x:317.4, y:809.8,	title:'Описание'}, 
{type:'Fort',	nameRU:'Ковчег',					name:'Ark',					x:410.1, y:850.3,	title:'Описание'}, 
{type:'Fort',	nameRU:'Край Торговца',				name:"Trader's Edge",		x:647.8, y:668,		title:'Описание'}, 
{type:'Fort',	nameRU:'Кулак Окрана',				name:"Okran's Fist",		x:764, y:466.9,		title:'Описание'}, 
{type:'Fort',	nameRU:'Лагерь Разбойников',		name:'Reaver Camp',			x:342.4, y:778.6,	title:'Описание'}, 
{type:'Fort',	nameRU:'Лагерь Разбойников',		name:'Reaver Camp',			x:383.4, y:795.7,	title:'Описание'}, 
{type:'Fort',	nameRU:'Лагерь Разбойников',		name:'Reaver Camp',			x:456.3, y:868,		title:'Описание'}, 
{type:'Fort',	nameRU:'Ловушка Нарко',				name:"Narko's Trap",		x:626.1, y:460.6,	title:'Описание'}, 
{type:'Fort',	nameRU:'Новая Кралия',				name:'New Kralia',			x:405.5,y:174.1,	title:'Описание'}, 
{type:'Fort',	nameRU:'Последний Бой',				name:'Last Stand',			x:350.2, y:169.3,	title:'Описание'}, 
{type:'Fort',	nameRU:'Путевая станция',			name:'Waystation',			x:157.6, y:272.2,	title:'Описание'}, 
{type:'Fort',	nameRU:'Путевая станция',			name:'Waystation',			x:415.6, y:257.9,	title:'Описание'}, 
{type:'Fort',	nameRU:'Путевая станция',			name:'Waystation',			x:464, y:392.5,		title:'Описание'}, 
{type:'Fort',	nameRU:'Путевая станция',			name:'Waystation',			x:537.7, y:600,		title:'Описание'}, 
{type:'Fort',	nameRU:'Рабские рынки',				name:'Slave Markets',		x:217.4, y:396.4,	title:'Описание'}, 
{type:'Fort',	nameRU:'Святая военная база',		name:'Holy Military Base',	x:599.3, y:289.6,	title:'Описание'}, 
{type:'Fort',	nameRU:'Святая военная база',		name:'Holy Military Base',	x:634.8, y:322.6,	title:'Описание'}, 
{type:'Fort',	nameRU:'Тайная наркоферма',			name:'Secret Drug Farm',	x:360, y:631.5,		title:'Описание'}, 
{type:'Fort',	nameRU:'Форт Мираж',				name:'Fort Mirage',			x:855.8, y:709.1,	title:'Описание'}, 
{type:'Fort',	nameRU:'Форт Симион',				name:'Fort Simion',			x:936.1, y:585.3,	title:'Описание'}, 
{type:'Fort',	nameRU:'Хранилище Теньгу',			name:"Tengu's Vault",		x:645.4, y:592.2,	title:'Описание'}, 
{type:'Fort',	nameRU:'Щит Окрана',				name:"Okran's Shield",		x:663.2, y:477.6,	title:'Описание'}, 
{type:'Mine',	nameRU:'Возрождение',				name:'Rebirth',				x:688.5, y:339,		title:'Описание'}, 
{type:'Mine',	nameRU:'Глазница',					name:'Eyesocket',			x:535.2, y:674.7,	title:'Описание'}, 
{type:'Mine',	nameRU:'Каменный лагерь',			name:'Stone Camp',			x:789.8, y:658.7,	title:'Описание'}, 
{type:'Mine',	nameRU:'Порт Север',				name:'Port North',			x:904.5, y:694.3,	title:'Описание'}, 
{type:'Mine',	nameRU:'Порт Юг',					name:'Port South',			x:803, y:797.4,		title:'Описание'}, 
{type:'Mine',	nameRU:'Рабская ферма',				name:'Slave Farm',			x:605, y:707.9,		title:'Описание'}, 
{type:'Mine',	nameRU:'Южная рабская ферма',		name:'Slave Farm South',	x:127.1, y:318.7,	title:'Описание'}, 
{type:'Mine',	nameRU:'Южный каменный лагерь',		name:'South Stone Camp',	x:668.2, y:719.6,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Башня Жестокости',			name:'Old Control Tower',	x:451.2, y:651.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Башня Жестокости',			name:'Tower of Abuse',		x:440.2, y:581.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Башня Ожога',				name:"Burn's Tower",		x:794.4, y:304.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Брошенный посёлок',			name:'Abandoned Town',		x:123.5, y:146.7,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Брошенный посёлок',			name:'Abandoned Town',		x:29.3, y:152.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Город-архив',				name:'Archive Town',		x:587.2, y:831.2,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Дрин',						name:'Drin',				x:833.5, y:585.2,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Жуткие руины',				name:'Horrible Ruin',		x:109, y:689.5,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Завод пауков',				name:'Spider Factory',		x:562.3, y:956.8,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Занятый роями арсенал',		name:'Hiver-Claimed Armoury',	x:132.6, y:669.6,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Занятый роями арсенал',		name:'Hiver-Claimed Armoury',	x:178, y:690.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Занятый роями арсенал',		name:'Hiver-Claimed Armoury',	x:206.9, y:636,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:198.8, y:55.8,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:309.7, y:849.6,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:339.8, y:963.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:505.4, y:504.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:583.9, y:530.9,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:617.8, y:507.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:920.4, y:228,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:944.6, y:260.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный арсенал',		name:'Lost Armoury',		x:963.5, y:305.5,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный город',			name:'Lost Town',			x:617.1, y:795.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затерянный склад доспехов',	name:'Lost Armour Store',	x:378.9, y:748.9,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Затопленные руины',			name:'Drowned Ruins',		x:715.8, y:378.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Клонящаяся башня',			name:'Leaning Tower',		x:764.3, y:286.5,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Маленькое селение',			name:'Tiny Settlement',		x:476.9, y:417.8,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мастерская в пустоши',		name:'Deadland Workshop',	x:516.8, y:534.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мастерская в пустоши',		name:'Deadland Workshop',	x:538.3, y:502.6,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мастерская в пустоши',		name:'Deadland Workshop',	x:591.3, y:494.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мастерская перепрошивки',	name:'Reprogramming Workshop',x:570.4, y:546.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мочалка',					name:'Bast',				x:797.1, y:542.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мёртвый улей',				name:'Deadhive Overrun',	x:672.7, y:292.9,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Мёртвый улей',				name:'Ruined Holy Outpost',	x:474, y:365,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Не-древняя мастерская',		name:'Post-Ancient Workshop',x:545.6, y:79.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Не-древняя мастерская',		name:'Post-Ancient Workshop',x:804.9, y:212.9,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пепельный купол I',			name:'Ashland Dome I',		x:181.2, y:820.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пепельный купол II',		name:'Ashland Dome II',		x:137.3, y:811.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пепельный купол III',		name:'Ashland Dome III',	x:149.4, y:860.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пепельный купол IV',		name:'Ashland Dome IV',		x:117.1, y:864.6,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Полицейские бараки',		name:'Police Barracks',		x:237.9, y:726.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Полицейские бараки',		name:'Police Barracks',		x:283.7, y:844.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Полицейские бараки',		name:'Police Barracks',		x:38.6, y:619.8,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пустая лаба',				name:'Empty Lab',			x:188.2, y:231,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Пустая лаба',				name:'Empty Lab',			x:193.4, y:204.6,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пустая лаба',				name:'Empty Lab',			x:225.5, y:230.2,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пустая лаба',				name:'Empty Lab',			x:737.4, y:304.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Пустая лаба',				name:'Empty Lab',			x:780.5, y:301,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Пустая развалина',			name:'Empty Ruin',			x:358.3, y:199.7,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Развалины путевой станции',	name:'Waystation Ruins',	x:416.6, y:812,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Развалины путевой станции',	name:'Waystation Ruins',	x:465.1, y:584.7,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Развалины фермы',			name:'Farm Ruins',			x:807, y:457.7,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Развалины фермы',			name:'Farm Ruins',			x:807, y:457.7,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Разграбленные руины',		name:'Looted Ruins',		x:663, y:789.3,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Разрушенная диспетчерская',	name:'Ruined Control Tower',x:447.6, y:618.2,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины арсенала',			name:'Armoury Ruin',		x:222.5, y:677.5,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины арсенала',			name:'Armoury Ruin',		x:233, y:110.8,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины арсенала',			name:'Armoury Ruin',		x:275.9, y:621.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины арсенала',			name:'Armoury Ruin',		x:521, y:550.9,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины арсенала',			name:'Armoury Ruin',		x:916, y:314.1,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины башни',				name:'Ruined Tower',		x:747.2, y:298.7,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины пепельного купола',	name:'Ashland Dome Ruin',	x:101.3, y:856.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины пепельного купола',	name:'Ashland Dome Ruin',	x:102.3, y:812.6,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины святой шахты',		name:'Holy Mine Ruin',		x:353, y:445.8,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины святой шахты',		name:'Holy Mine Ruin',		x:557.3, y:455,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Руины святой шахты',		name:'Holy Mine Ruin',		x:598.5, y:445.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Свободное селение',			name:'Free Settlement',		x:382.6, y:693.2,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая деревня',			name:'Old Village',			x:792, y:758.4,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая деревня',			name:'Old Village',			x:852, y:291.1,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая имперская башня',	name:'Old Empire Watchtower',	x:315.3, y:924.9,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая имперская башня',	name:'Old Empire Watchtower',	x:919.9, y:192.1,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая имперская башня',	name:'Old Empire Watchtower',	x:930.5, y:283.8,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая линия фронта',		name:'Old Frontlines',		x:290, y:156.9,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая мастерская',			name:'Dead Workshop',		x:268.9, y:920.2,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Старая тюрьма',				name:'The Old Prison',		x:208.6, y:533,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Упавшая башня',				name:'Fallen Tower',		x:294.9, y:112.1,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Упавшая башня',				name:'Fallen Tower',		x:461.2, y:161.5,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Упавшая башня',				name:'Fallen Tower',		x:768.1, y:295.3,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Упавшая башня',				name:'Fallen Tower',		x:964.4, y:187,			title:'Описание'}, 
{type:'Ruins',		nameRU:'Форпост затерянной библиотеки',		name:'Lost Library Outpost',		x:350.7, y:310.4,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Форпост снабжения старой империи',	name:'Old Empire Supply Outpost',	x:223.8, y:745,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Форпост снабжения старой империи',	name:'Old Empire Supply Outpost',	x:287, y:802.4,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Форпост снабжения старой империи',	name:'Old Empire Supply Outpost',	x:305.7, y:738.6,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Цеховый комплекс',			name:'Workshop Complex',	x:261.9, y:236.9,	title:'Описание'}, 
{type:'Ruins',		nameRU:'Шекские руины',				name:'Shek Ruins',		x:443.5,y:227.9,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Экспедиция 4',				name:'Expedition 4',	x:346.1, y:825.9,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Экспедиция 5',				name:'Expedition 5',	x:289.4, y:758.7,		title:'Описание'}, 
{type:'Ruins',		nameRU:'Эндин',						name:'Endin',			x:839.6, y:520.4,		title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Древние лабы',			name:'Ancient Labs',	x:327.5, y:446.3,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Древние лабы',			name:'Ancient Labs',	x:610.8, y:977.7,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Древние лабы',			name:'Ancient Labs',	x:696.4, y:237.5,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Древние лабы',			name:'Ancient Labs',	x:758.4, y:296.5,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Древняя техно лаба',	name:'Ancient Tech Lab',x:267.1, y:31.6,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Древняя техно лаба',	name:'Ancient Tech Lab',x:904.8, y:102.7,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Заболоченная лаба',		name:'Swamped Lab',		x:239.5, y:221.7,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Заболоченная лаба',		name:'Swamped Lab',		x:304.1, y:305.4,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Заражённая лаба',		name:'Infested Lab',	x:319, y:386.2,				title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:149.3, y:175.4,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:163.7, y:65.6,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:176.6, y:105,				title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:188, y:145.4,				title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:216.7, y:75.9,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:236.7, y:127.8,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:413.4, y:129.5,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:706.2, y:371.3,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:950.9, y:481.9,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:967.7, y:229.5,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Островная лаба',		name:'Island Lab',		x:56.9, y:443.4,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Осыпающиеся лабы',		name:'Crumbling Labs',	x:336.4, y:700.7,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Подозрительная лаба',	name:'Suspicious Lab',	x:817, y:315.8,				title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Руины библиотеки',		name:'Library Ruins',	x:124.6, y:109.1,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Руины библиотеки',		name:'Library Ruins',	x:85.7, y:180.1,			title:'Описание'}, 
{type:'RuinsLab',	nameRU:'Руины лабы',			name:'Lab Ruin',		x:205.4, y:229.2,			title:'Описание'}, 
{type:'Village',	nameRU:'Гниль',					name:'Rot',						x:395.9, y:362.4,	title:'Описание'}, 
{type:'Village',	nameRU:'Город из грязи',		name:'Mud Town',				x: 363.9, y:352.3,	title:'Описание'}, 
{type:'Village',	nameRU:'Далёкая деревня Улья',	name:'Distant Hive Village',	x:908.7, y:617.8,	title:'Описание'}, 
{type:'Village',	nameRU:'Далёкая деревня Улья',	name:'Distant Hive Village',	x:975.5, y:606.8,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня Каменных Крыс',	name:'Stone Rat Village',		x:287.4, y:349.5,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня Оседлых Кочевников',name:'Settled Nomad Village',x:662.1, y:117.9,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня Отщепенцев',	name:'Flotsam Village',			x:787.1, y:369.1,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня Серодёров',		name:'Grayflayer Village',		x:363.6, y:382.4,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня культистов',	name:'Cult Village',			x:513.7, y:815.9,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня на болоте',		name:'Swamp Village',			x:320, y:319.9,		title:'Описание'}, 
{type:'Village',	nameRU:'Деревня на болоте',		name:'Swamp Village',			x:385.1, y:289.7,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня собирателей',	name:'Gatherer Village',		x:636.3, y:108.5,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня собирателей',	name:'Gatherer Village',		x:642, y:139,		title:'Описание'}, 
{type:'Village',	nameRU:'Деревня южного улья',	name:'Southern Hive Village',	x:176.9, y:586.7,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня южного улья',	name:'Southern Hive Village',	x:247.6, y:648.9,	title:'Описание'}, 
{type:'Village',	nameRU:'Деревня-призрак',		name:'Ghost Village',			x:857.1, y:379,		title:'Описание'}, 
{type:'Village',	nameRU:'Западный улей',			name:'Western Hive',			x:572, y:51.8,		title:'Описание'}, 
{type:'Village',	nameRU:'Оседлые кочевники',		name:'Settled Nomads',			x:425.5, y:443,		title:'Описание'}, 
{type:'Village',	nameRU:'Первая деревня',		name:'First Village',			x:986.8, y:467.3,	title:'Описание'}, 
{type:'Village',	nameRU:'Рыбацкая деревня',		name:'Fishing Village',			x:507.6, y:869.6,	title:'Описание'}, 
{type:'Village',	nameRU:'Рыбацкая деревня',		name:'Fishing Village',			x:851.8, y:414.6,	title:'Описание'}, 
{type:'Village',	nameRU:'Рыбацкая деревня-призрак',name:'Dead Fishing Village',	x:79.3, y:592.7,	title:'Описание'}, 
{type:'Village',	nameRU:'Святая ферма',			name:'Holy Farm',		x:578, y:350,		title:'Описание'}, 
{type:'Village',	nameRU:'Святая ферма',			name:'Holy Farm',		x:602, y:378,		title:'Описание'}, 
{type:'Village',	nameRU:'Святая ферма',			name:'Holy Farm',		x:606, y:330,		title:'Описание'}, 
{type:'Village',	nameRU:'Святая ферма',			name:'Holy Farm',		x:646, y:428,		title:'Описание'}, 
{type:'Village',	nameRU:'Святая ферма',			name:'Holy Farm',		x:696, y:438.4,		title:'Описание'}, 
{type:'Village',	nameRU:'Святая ферма',			name:'Holy Farm',		x:737.3, y:417,		title:'Описание'}, 
{type:'Village',	nameRU:'Святые шахты',			name:'Holy Mines',		x:509, y:433,		title:'Описание'}, 
{type:'Village',	nameRU:'Святые шахты',			name:'Holy Mines',		x:541, y:363,		title:'Описание'}, 
{type:'Village',	nameRU:'Святые шахты',			name:'Holy Mines',		x:550, y:412,		title:'Описание'}, 
{type:'Village',	nameRU:'Святые шахты',			name:'Holy Mines',		x:615, y:415,		title:'Описание'}, 
{type:'Village',	nameRU:'Святые шахты',			name:'Holy Mines',		x:632, y:294,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:464, y:129,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:482, y:207,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:502, y:280,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:514, y:170,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:515, y:230,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:517, y:122,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:594, y:144,		title:'Описание'}, 
{type:'Village',	nameRU:'Улей',					name:'Hive Village',	x:680.7, y:171.8,	title:'Описание'}, 
{type:'Village',	nameRU:'Фермерская деревня',	name:'Farming Village',	x:522.4, y:763.8,	title:'Описание'}, 


];

/*
{type:'noneMe',	nameRU:'База наёмников',	name:'Mercenary base',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Башня Ожога',		name:'Unknown Tower',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Башня Тумана',		name:'Tower',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Бугристый Холм',	name:'Blister Hill',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Военная застава',	name:'Military Outpost',	x:000, y:000,	title:'Описание'}, 
{type:'noneMe',	nameRU:'Волчье логово',		name:'Wolf Den',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Гиблый двор',		name:'Fog Deathyard',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Гнездо болотных ящеров',name:'Swamp Raptor Nest',	x:000, y:000,	title:'Описание'}, 
{type:'noneMe',	nameRU:'Гнездо горилл',		name:'Gorillo Nest',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Гнездо гурчащих',	name:'Gurgler Nest',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Гнездо клювастых',	name:'Nest of Beak Things',	x:000, y:000,	title:'Описание'}, 
{type:'noneMe',	nameRU:'Гнездо крабов',		name:'Crab Nest',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Гнездо рвачей',		name:'Skimmer Nest',	x:000, y:000,		title:'Описание'}, 
{type:'noneMe',	nameRU:'Дом Кожи - Штаб',	name:'Creepy Outpost',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Жуткие руины',			name:'Nice Ruin',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Завод пауков',			name:'Factory',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Затерянная библиотека',	name:'Lost Library',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Затерянный арсенал',	name:'Outpost',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Имперская деревня',		name:'Empire Village',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь Белой Брови',	name:'White Eyebrow Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь Кровавых Бандитов',name:'Blood Bandit Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь Охотников за наградой',name:'Bounty Hunter Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь Пыльных бандитов',		name:'Dust Bandit Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь Разбойников',			name:'Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь Чёрного Дракона',		name:'Black Dragon Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь бродяг',				name:'Vagrant Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь козлопасов',			name:'Goat Herder's Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь налётчиков',			name:'Raider Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь наёмников',			name:'Mercenary Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь рабовладельцев',		name:'Slaver Camp',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Лагерь- Охотники на людоедов',name:'Camp- Cannibal Hunters',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Ловушка Нарко',				name:'Narko's Trap',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Логово Костяного Волка',	name:'Boneyard Wolf Den',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Малое гнездо рвачей',		name:'Small Skimmer Nest',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Нападение гиблого двора',	name:'Fog Deathyard Invasion',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Нашествие людоедов',		name:'Cannibal Infestation',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Нашествие туманников',		name:'Fogman Nest Invasion',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Нигде',						name:'Nowhere',	x:000, y:000,					title:'Описание'}, 
{type:'noneMe',	nameRU:'Ограбленный караван',		name:'Raided Caravan',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Пустая развалина',			name:'Ruins',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Пустые развалины',			name:'Empty Ruins',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Путевая станция четыре',	name:'Waystation Four',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Рабские рынки',				name:'Market',	x:000, y:000,					title:'Описание'}, 
{type:'noneMe',	nameRU:'Развалины фермы',			name:'Farm Ruin',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Разведпост',				name:'Building',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Разрушенная ферма',			name:'Ruined Farm',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Речное гнездо',				name:'River Nest',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Ровная лагуна',				name:'Strange Town',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Руины лабы',				name:'Ruin',	x:000, y:000,					title:'Описание'}, 
{type:'noneMe',	nameRU:'Рыбацкая деревня',			name:'Village',	x:000, y:000,					title:'Описание'}, 
{type:'noneMe',	nameRU:'Свободное селение',			name:'Ruined Town',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Свободный город',			name:'The Free City',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Ска',						name:'Ska',	x:000, y:000,						title:'Описание'}, 
{type:'noneMe',	nameRU:'Ссылка Кат-Лона',			name:'Ominous Place',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Старая диспетчерская',		name:'Old Tower',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Трон Хозяина Жуков',		name:'Throne of the Bugmaster',	x:000, y:000,	title:'Описание'}, 
{type:'noneMe',	nameRU:'Убежище Отщепенцев',		name:'Lone Shack',	x:000, y:000,				title:'Описание'}, 
{type:'noneMe',	nameRU:'Упавшая башня',				name:'Unknown Object',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Форт Ямуса',				name:'Fort Yabuta',	x:000, y:000,			title:'Описание'}, 
{type:'noneMe',	nameRU:'Южный улей',				name:'Hive',	x:000, y:000,			title:'Описание'}, 

*/


